desc: The remote Neotoma database.
name: neotoma
dsn: postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRESS_PORT}/${POSTGRES_DB}
docPath: doc/schema
requiredVersion: '>= 1.42, < 2'
format:
  # Adjust the column width of Markdown format table
  # Default is false
  adjust: true
  # Sort the order of table list and columns
  # Default is false
  sort: true
  # Display sequential numbers in table rows
  # Default is false
  number: true
  # The comments for each table in the Tables section of the index page will display the text up to the first double newline (first paragraph).
  # Default is false
  showOnlyFirstParagraph: false
  # Hide table columns without values
  # Default is false
  hideColumnsWithoutValues: false
  # It can be boolean or array
  # hideColumnsWithoutValues: ["Parents", "Children"]
er:
  # Skip generation of ER diagram
  # Default is false
  skip: false
  # ER diagram image format (`png`, `jpg`, `svg`, `mermaid`)
  # Default is `svg`
  format: svg
  # Add table/column comment to ER diagram
  # Default is false
  comment: false
  # Hide relation definition from ER diagram
  # Default is false
  hideDef: false
  # Show column settings in ER diagram. If this section is not set, all columns will be displayed (default).
  showColumnTypes:
    # Show related columns
    related: true
    # Show primary key columns
    primary: true
  # Distance between tables that display relations in the ER
  # Default is 1
  distance: 2
  # ER diagram (png/jpg) font (font name, font file, font path or keyword)
  # Default is "" (system default)
  font: Mandali
# .tbls.yml
lint:
  # require table comment
  requireTableComment:
    enabled: true
    # all commented, or all uncommented.
    allOrNothing: false
  # require column comment
  requireColumnComment:
    enabled: true
    # all commented, or all uncommented.
    allOrNothing: true
    # exclude columns from warnings
    exclude:
      - id
      - recdatecreated
      - recdatemodified
    # exclude tables from warnings
    excludeTables:
      - logs
      - comment_stars
  # require index comment
  requireIndexComment:
    enabled: true
    # all commented, or all uncommented.
    allOrNothing: false
    # exclude indexes from warnings
    exclude:
      - user_id_idx
    # exclude tables from warnings
    excludeTables:
      - logs
      - comment_stars
  # require constraint comment
  requireConstraintComment:
    enabled: true
    # all commented, or all uncommented.
    allOrNothing: false
    # exclude constrains from warnings
    exclude:
      - unique_user_name
    # exclude tables from warnings
    excludeTables:
      - logs
      - comment_stars
  # require trigger comment
  requireTriggerComment:
    enabled: true
    # all commented, or all uncommented.
    allOrNothing: false
    # exclude triggers from warnings
    exclude:
      - update_count
    # exclude tables from warnings
    excludeTables:
      - logs
      - comment_stars
  # require table labels
  requireTableLabels:
    enabled: true
    # all commented, or all uncommented.
    allOrNothing: false
    # exclude tables from warnings
    exclude:
      - logs
  # find a table that has no relation
  unrelatedTable:
    enabled: true
    # all related, or all unrelated.
    allOrNothing: true
    # exclude tables from warnings
    exclude:
      - logs
  # check max column count
  columnCount:
    enabled: true
    max: 10
    # exclude tables from warnings
    exclude:
      - user_options
  # require columns
  requireColumns:
    enabled: true
    columns:
      -
        name: redcatecreated
      -
        name: recdatemodified
        exclude:
          - logs
          - CamelizeTable
  # check duplicate relations
  duplicateRelations:
    enabled: true
  # check if the foreign key columns have an index
  requireForeignKeyIndex:
    enabled: true
    exclude:
      - comments.user_id
  # checks if labels are in BigQuery style (https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements)
  labelStyleBigQuery:
    enabled: true
    exclude:
      - schema_migrations
  # checks if tables are included in at least one viewpoint
  requireViewpoints: 
    enabled: true
    exclude:
      - schema_migrations
# .tbls.yml
include:
  - ndb.*
  - ti.*
  - ap.*
  - ts.*
  - doi.*
exclude:
  - public.*
templates:
  md:
    index: 'templates/index.md.tmpl'
    table: 'templates/table.md.tmpl'
viewpoints:
  - 
    name: Controlled Vocabularies
    desc: Tables with controlled vocabularies.
    tables:
      - ndb.agetypes
      - ndb.chroncontroltypes
      - ndb.elementtaxagroups
      - ndb.elementmaturities
      - ndb.elementsymmetries
      - ndb.externaldatabases
      - ndb.calibrationprograms
      - ndb.calibrationcurves
      - ndb.analysisunitaltdepthscales
      - ndb.datasettaxagrouptypes
      - ndb.lakeparametertypes
      - ndb.elementtypes
      - ndb.eventtypes
      - ndb.isobiomarkerbandtypes
      - ndb.isobiomarkertypes
      - ndb.isoinstrumentationtypes
      - ndb.isomaterialanalyzedtypes
      - ndb.isopretreatmenttypes
      - ndb.depenvttypes  
  - 
    name: Hierarchical Tables
    desc: Tables with internal hierarchies.
    tables:
      - ndb.taxa
      - ndb.chroncontroltypes
      - ndb.lithostrat
      - ndb.rocktypes
      - ndb.taxaalthierarchy
      - ndb.depenvttypes
  - 
    name: Taxonomic Tables
    desc: Tables related to species, observations and specimens.
    tables:
      - ndb.taxa
      - ndb.externaltaxa
      - ndb.formtaxa
      - ndb.taxaalthierarchy
      - ndb.taxaalthierarchytypes
      - ndb.taxonpaths
  -
    name: Dataset related tables
    desc: Tables that help define and structure datasets.
    tables:
       - ap.querytable
       - ndb.datasets
       - ndb.datasettypes
       - ndb.datasetpis
       - ndb.datasetdatabases
       - ndb.datasetdoi
       - ndb.datasetpublications
       - ndb.datasetsubmissions
       - ndb.datasetsubmissiontypes
       - ndb.datasettaxagrouptypes
       - ndb.datasettaxonnotes
       - ndb.datasetvariables
  -
    name: Contact related tables
    desc: Tables that relate to people, or are connected to the contactid.
    tables:
      - ti.stewards
      - ti.stewardupdates
      - ap.datasetpisauthors
      - ap.querytable
      - ndb.chronologies
      - ndb.collectors
      - ndb.contactreferences
      - ndb.contacts
      - ndb.dataprocessors
      - ndb.datasetpis
      - ndb.datasetsubmissions
      - ndb.datasettaxonnotes
      - ndb.datataxonnotes
      - ndb.externalcontacts
      - ndb.publicationauthors
      - ndb.sampleanalysts
      - ndb.synonymy
  -
    name: Chronology related tables
    desc: Tables related to chronology and age assignments.
    tables:
      - ap.querytable
      - ndb.accumulationrates
      - ndb.aggregatechronologies
      - ndb.aggregatesampleages
      - ndb.calibrationcurves
      - ndb.calibrationprograms
      - ndb.chroncontrolaccuracydirections
      - ndb.chroncontrolaccuracydistributions
      - ndb.chroncontrolaccuracyranks
      - ndb.chroncontrolprecisionranks
      - ndb.chroncontrolranks
      - ndb.chroncontrols
      - ndb.chroncontrolscal14c
      - ndb.chroncontroltypes
      - ndb.chronologies
      - ndb.eventchronology
      - ndb.events
      - ndb.eventtypes
      - ndb.externalgeochronology
      - ndb.geochroncontrols
      - ndb.geochronology
      - ndb.geochronpublications
      - ndb.geochrontypes
      - ndb.hiatuschronology
      - ndb.hiatuses
      - ndb.radiocarbon
      - ndb.radiocarboncalibration
      - ndb.radiocarbonmethods
      - ndb.relativeagepublications
      - ndb.relativeages
      - ndb.relativeagescales
      - ndb.relativechronology
      - ndb.sampleages
      - ndb.specimendates
      - ndb.uraniumseries
      - ndb.uraniumseriesdata
      