CREATE ROLE "admin" WITH 
	NOSUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOLOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;

CREATE ROLE "neotomaAdmin" WITH 
	NOSUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	LOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1
	VALID UNTIL '+292278994-08-16T15:00';

GRANT rds_superuser TO "neotomaAdmin";

CREATE ROLE readonlyinternal WITH 
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOLOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;

GRANT USAGE ON SCHEMA ndb TO readonlyinternal;
GRANT SELECT ON ALL TABLES IN SCHEMA ndb TO readonlyinternal;

GRANT USAGE ON SCHEMA ap TO readonlyinternal;
GRANT SELECT ON ALL TABLES IN SCHEMA ap TO readonlyinternal;

GRANT USAGE ON SCHEMA doi TO readonlyinternal;
GRANT SELECT ON ALL TABLES IN SCHEMA doi TO readonlyinternal;

GRANT USAGE ON SCHEMA da TO readonlyinternal;
GRANT SELECT ON ALL TABLES IN SCHEMA da TO readonlyinternal;

GRANT USAGE ON SCHEMA ndb TO readonlyinternal;
GRANT SELECT ON ALL TABLES IN SCHEMA ndb TO readonlyinternal;

CREATE ROLE neotomaapidev IN ROLE readonlyinternal;
ALTER ROLE neotomaapidev WITH
    LOGIN
    PASSWORD 'testlogin';

CREATE ROLE tankreader;
CREATE ROLE functionwriter;

CREATE ROLE neotomaapidev WITH 
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	LOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;

CREATE ROLE prodapireadonly IN ROLE ;

CREATE ROLE devtiliareadwrite
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	LOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;

CREATE ROLE prodtiliareadwrite
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	LOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;

CREATE ROLE jkn128;
CREATE ROLE nhoffman;
CREATE ROLE ondrej;
CREATE ROLE sedv8808;
CREATE ROLE sug335;

